### ISSUE TITLE
Missing chai-smoothie as a dev dependency

### ISSUE THREAD

**Issue by burkilic** [serenity-js/tutorial-from-scripts-to-serenity#1]
Hello, package.json is missing chai-smoothie as one of its dev dependencies.

**Comment by jan-molak** [comment]
Hello @burkilic! `chai-smoothie` is not required to complete the tutorial (although useful to assert on visibility of on-screen elements in your daily work with protractor).

Is there any particular error that you're seeing?

Thanks!
Jan

**Comment by burkilic** [comment]
Hello, thanks for the quick reply. So it was complaining about not finding "node_modules/chai-smoothie/lib/chai-smoothie.d.ts". I suspect this because of the following in tsconfig.json:

"files": [
    "node_modules/chai-smoothie/lib/chai-smoothie.d.ts"
  ],

**Comment by jan-molak** [comment]
Thanks, well spotted!
