### ISSUE TITLE
http://todomvc.com is not there anymore

### ISSUE THREAD

**Issue by ntdaley** [serenity-js/tutorial-from-scripts-to-serenity#12]
Going to http://todomvc.com leads to a page saying that it is a parked domain.

Which, of course means the tests in this tutorial no longer pass.

**Comment by jan-molak** [comment]
Thanks @ntdaley - yeah, I noticed that this morning. I'll need to deploy a standalone version of todomvc somewhere if the main one doesn't come back up.

**Comment by jan-molak** [comment]
...and http://todomvc.com/ it's back up. Regardless, the tutorial should run against something under the serenity-js.org domain. I'll add it to my list.
