### ISSUE TITLE
E/launcher - Process exited with error code 100

### ISSUE THREAD

**Issue by KumarSatajyoti** [serenity-js/tutorial-from-scripts-to-serenity#9]
E/launcher - Process exited with error code 100 when trying to run npm test

**Comment by jan-molak** [comment]
Hi @KumarSatajyoti, it will be quite difficult for me to help out without any more context, I'm afraid.
I'll close this ticket as #10 seems to be talking about a similar issue and provides a bit more detail.

Thanks,
Jan
